/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poli_ap2_jtable;



import javax.swing.DefaultCellEditor;  // Importa la clase DefaultCellEditor del paquete javax.swing, que proporciona un editor de celdas predeterminado para usar en componentes de tabla.
import javax.swing.JComboBox;  // Importa la clase JComboBox del paquete javax.swing, que proporciona un componente de lista desplegable.
import javax.swing.JFrame;  // Importa la clase JFrame del paquete javax.swing, que representa una ventana de la interfaz de usuario.
import javax.swing.JOptionPane;  // Importa la clase JOptionPane del paquete javax.swing, que proporciona cuadros de diálogo modales para mensajes de advertencia, información, error, etc.
import javax.swing.JTable;  // Importa la clase JTable del paquete javax.swing, que representa una tabla para mostrar datos en filas y columnas.
import javax.swing.table.DefaultTableModel;  // Importa la clase DefaultTableModel del paquete javax.swing.table, que proporciona un modelo de tabla predeterminado.
import javax.swing.*;  // Importa todos los elementos del paquete javax.swing, lo cual incluye muchos componentes de la interfaz de usuario.
import java.awt.print.*;  // Importa las clases relacionadas con la impresión de Java AWT (Abstract Window Toolkit), que permite la impresión de componentes gráficos en Java.
import java.text.MessageFormat;  // Importa la clase MessageFormat del paquete java.text, que formatea mensajes de texto en Java.

/**
 *
 * @author Harol
 */
public class Tabla extends javax.swing.JFrame {

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Usu1", "Poli", "AP2", "Sur"},
                {"Usu2", "Poli", "AP2", "Sur"},
                {"Usu3", "Poli", "AP2", "Sur"},
                {"Usu4", "Poli", "AP2", "Sur"},
                {"Usu5", "Poli", "AP2", "Sur"},
                {"Usu6", "Poli", "AP2", "Sur"},
                {"Usu7", "Poli", "AP2", "Sur"},
                {"Usu8", "Poli", "AP2", "Sur"},
                {"Usu9", "Poli", "AP2", "Sur"},
                {"Usu10", "Poli", "AP2", "Sur"},
                {"Usu11", "Poli", "AP2", "Sur"},
                {"Usu12", "Poli", "AP2", "Sur"},
                {"Usu13", "Poli", "AP2", "Sur"},
                {"Usu14", "Poli", "AP2", "Sur"},
                {"Usu15", "Poli", "AP2", "Sur"}
            },
            new String [] {
                "Nombre", "Apellidos", "Asignatura", "Sede"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tablas Ejemplo Politecnico Internacional");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poli_ap2_jtable/Poli.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
// Intenta imprimir la tabla jTable1 con un encabezado y un pie de página predefinidos.
try {
    // Crea un objeto MessageFormat para el encabezado del documento a imprimir.
    MessageFormat header = new MessageFormat("Tablas Ejemplo de Impresion Politecnico Internacional");

    // Crea un objeto MessageFormat para el pie de página del documento a imprimir.
    MessageFormat footer = new MessageFormat("Página {0}");

    // Intenta imprimir la tabla jTable1 con el modo FIT_WIDTH, utilizando el encabezado y el pie de página definidos.
    try {
        jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
    } catch (PrinterException ex) {  // Captura cualquier excepción relacionada con la impresión.
        // Si se produce una excepción, lanza una nueva RuntimeException con un mensaje de error y la excepción original.
        throw new RuntimeException("Error de impresión", ex);
    }

    // Muestra un mensaje de diálogo indicando que la impresión se ha completado correctamente.
    JOptionPane.showMessageDialog(rootPane, "Impresión completada", getTitle(), JOptionPane.INFORMATION_MESSAGE);

// Si se produce una excepción del tipo RuntimeException en el bloque anterior, se captura aquí.
} catch (RuntimeException ex) {
    // Muestra un mensaje de diálogo indicando que ha habido un fallo en la impresión y muestra el mensaje de error.
    JOptionPane.showMessageDialog(null, "Falla de impresión\n" + ex.getMessage());
}


        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
